# Generated by Django 4.2.11 on 2024-04-25 23:38

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField, JSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.TextField()),
                ('height', models.TextField()),
                ('weight', models.TextField()),
                ('drugs', ArrayField(models.TextField())),
                ('tests', ArrayField(models.TextField())),
                ('illness', ArrayField(models.TextField())),
                ('recommendations', ArrayField(models.TextField())),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.doctor')),
            ],
        ),
    ]
