# Generated by Django 5.0.4 on 2024-05-17 19:45

import dicom.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_alter_dicomimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomimage',
            name='file',
        ),
        migrations.CreateModel(
            name='DICOMImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dicom.models.dicom_image_upload_path)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dicom.dicomimage')),
            ],
        ),
    ]
